### ISSUE TITLE
Add a CD workflow using github actions to deploy to firebase.

### ISSUE THREAD

**Issue by avinash-vk** [acmpesuecc/weatherly#1]
Add a continuous deployment workflow using github actions, so that every time a pull request is merged into master, it gets automatically deployed to the firebase server and changes are reflected on the website.
The firebase ci token is saved in the secrets and is named "FIREBASE_TOKEN" and can be accessed in the workflows file.

**Comment by RakshithRAcharya** [comment]
Hey.....Where exactly is the FIREBASE_TOKEN
Is it there in the repo?

**Comment by RakshithRAcharya** [comment]
Found It...sorry

**Comment by RakshithRAcharya** [comment]
We can't access the secrets in this repo and secrets are not passed to workflows that are triggered by a pull request from a fork.So what to do??

**Comment by avinash-vk** [comment]
Im so sorry about the delay! But dont worry your code would solve it. Basically ive stored the secret in my settings of the github account so that it is not publically accessible.
