### ISSUE TITLE
Add the logo configurations to the webapp and clean up

### ISSUE THREAD

**Issue by avinash-vk** [acmpesuecc/weatherly#13]
Here are the set of tasks:
- Change the title of the app on the title bar to weatherly in `index.html`.
- Change the logo of the app to either `weatherly.ico` in the `public` directory or any of the non default logos that you like. 
- Remove `favicon.ico`, and the default logos in the `public` folder.

**Comment by NicolaDonoastro** [comment]
Hello @avinash-vk Can i give it a try, I am new to the open-source community and looking forward to opportunities to contribute

**Comment by avinash-vk** [comment]
Sure go ahead!
