### ISSUE TITLE
Design a logo for the web-app.

### ISSUE THREAD

**Issue by avinash-vk** [acmpesuecc/weatherly#2]
Well do you wanna put your design skills to test? This one's for you. 
- Make a simple logo and retrieve it in a png format for two sizes - "192 x 192" and "512 x 512", and add it to the `public` folder of the repository under the name `weatherlyLogo192.png` and `weatherLogo512.png`. 
- You will also have to create a `weatherly.ico` icon file for the same logo. You can use [this](https://favicon.io/) to generate the favicon file from a png image file.

Don't go overboard, even though you can. Make sure it fits the theme of the application and involves a combination of weather and time.

**Comment by RakshithRAcharya** [comment]
Hey! Can I work on this

**Comment by avinash-vk** [comment]
Sure go ahead @RakshithRAcharya !

**Comment by anushkadeshpande** [comment]
Hey I've attempted to make the icon and sent a pull request

**Comment by avinash-vk** [comment]
okay @anushkadeshpande  will look into it !
