### ISSUE TITLE
Add API call to fetch time data from http://worldtimeapi.org

### ISSUE THREAD

**Issue by avinash-vk** [acmpesuecc/weatherly#6]
In the `api/Time.js` file, make an api request using `fetch` or `axios` whichever you prefer and get the weather data from a location that is accepted as a parameter in the `GET_TIME` function and return the data.

**Comment by shaneiadt** [comment]
I assume we would need to match some location search parameter to get the available timezones here correct? 😄 

http://worldtimeapi.org/api/timezone/

For example:

- Search "**Athens**"
- Check timezone list and build valid URL

=> http://worldtimeapi.org/api/timezone/Europe/Athens

If so assign me, please 👍

**Comment by avinash-vk** [comment]
> I assume we would need to match some location search parameter to get the available timezones here correct? 
> 
> http://worldtimeapi.org/api/timezone/
> 
> For example:
> 
> * Search "**Athens**"
> * Check timezone list and build valid URL
> 
> => http://worldtimeapi.org/api/timezone/Europe/Athens
> 
> If so assign me, please

Okay that's right @shaneiadt ! But for this issue, the only expected outcome is a function that takes in a valid location as a parameter and the function would return the data received from the API as it is. Cleaning/Processing the data would be ideally done later. Thanks for your interest!
You can go ahead and work on it :D
