### ISSUE TITLE
Add the navbar component with routing to landing and dashboard

### ISSUE THREAD

**Issue by avinash-vk** [acmpesuecc/weatherly#7]
Add a Navbar to the web-app preferably using the material-ui library for react. Make sure to include a logo (can be the react logo available in the `public` folder) , the weatherly title and routes to the dashboard and Landing page as links on the navbar.

**Comment by ShreyaPanale** [comment]
Hey @avinash-vk , I would like to work on this issue!

**Comment by avinash-vk** [comment]
> Hey @avinash-vk , I would like to work on this issue!

Sure go ahead!!

**Comment by abhishek-pes** [comment]
hey @avinash-vk  can i work on this

**Comment by avinash-vk** [comment]
Sure @abhishek-pes ! But another contributor has already made a PR for this that's yet to be merged, It would be awesome if you could try out #4  or any of the other issues? That way more issues can make way into the repo after the first set's out!
